Mr 70 product page implementation
JaqKent/mundoregalo-frontend pull request #31
Opened 2023-05-22 08:25 UTC by JaqKent

first part of the product page implementation

2023-05-22 15:42 UTC, nathan-hyan requested changes
Some comments before moving on

2023-05-22 15:42 UTC, nathan-hyan requested changes
Some comments before moving on

2023-05-23 14:06 UTC, JaqKent commented on src/components/CustomButton/index.tsx
> +                } ${secondary ? styles.secondaryButton : styles.primaryButton}`}
done

2023-05-23 14:06 UTC, JaqKent commented on src/components/CustomButton/styles.module.scss
> +    border-radius: 15px;
done

2023-05-23 14:07 UTC, JaqKent commented on src/components/ProductPage/components/SelectDropdown/index.tsx
> +    const [selectedOption, setSelectedOption] = useState<string>();
done

2023-05-23 14:07 UTC, JaqKent commented on src/components/ProductPage/components/SelectDropdown/index.tsx
> +/* eslint-disable no-param-reassign */
removed

2023-05-23 14:09 UTC, JaqKent commented on src/components/ProductPage/components/SelectDropdown/index.tsx
> +    const selectChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
done

2023-05-23 14:11 UTC, JaqKent commented on src/components/ProductPage/components/StarRating/index.tsx
> +    const [ratingValue, setRatingValue] = useState(0);
the component use the state when the user click on the "star" for puntuate the product

2023-05-23 14:15 UTC, JaqKent commented on src/components/ProductPage/components/quantitySelector/index.tsx
> +    };
done

2023-05-23 14:15 UTC, JaqKent commented on src/components/ProductPage/index.tsx
> +                    poppinText
ok , i just use the placeholder from the design

2023-05-23 14:16 UTC, JaqKent commented on src/components/Slider/index.tsx
>  /* eslint-disable no-unused-vars */
removed

2023-05-23 14:22 UTC, JaqKent commented on src/components/CustomButton/index.tsx
> +                onClick={isSubmit ? undefined : onClick}
done

2023-05-23 14:35 UTC, JaqKent commented on src/components/Slider/index.tsx
> +    slides: { id: number; img: string }[];
done

2023-05-23 15:06 UTC, nathan-hyan approved these changes

2023-05-23 15:08 UTC, merged