mr-85-86-87-88-89-visual fixes and search screen
JaqKent/mundoregalo-frontend pull request #40
Opened 2023-09-25 14:33 UTC by JaqKent

visual bugs fixes,search bar implementation and product screen for the search

2023-09-25 23:35 UTC, nathan-hyan requested changes
Commentsss

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +                    onClick={() => handleSearch(search)}
No hay necesidad de pasarle search a la función si es un estado, directamente usa el estado en la función y acá podes resumir a  `onClick={handleSearch}`

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +        setSearch(searchItem);
Porque volves a setear Search al mismo search?

Si ya tenes el valor de Search en el estado, borra esta linea y navega directamente a `/productsearch/${search}`

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +        navigate(`/productsearch/${searchItem}`);
Siempre camelCase

`productSearch`

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +    }).slice(0, 10);
Esto puede ir en un `utils.ts`

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +                            onKeyDown={() => handleSearch(item.description)}
Usas un `onKeyDown`, pero que tecla estas escuchando específicamente?

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/components/ProductSearchScreen/index.tsx
> +                    discountPrice={product.discountPrice || undefined}
El `|| undefined` es completamente innecesario

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/components/specifications/index.tsx
> +            </div>
Aca tmb

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/components/specifications/index.tsx
> +            </div>
Aca tmb

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/components/specifications/styles.module.scss
> +    @include flex (center, center, column);
```suggestion
    @include flex(center, center, column);
```

Guarda con los espacios innecesarios

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/components/specifications/styles.module.scss
>      @include flex (flex-start, flex-start, column);
```suggestion
    @include flex(flex-start, flex-start, column);
```

Aca tmb

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/styles.module.scss
> +
Espacio innecesario

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/styles.module.scss
> +
Aca tmb

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/styles.module.scss
> +
Guarda con los espacios innecesarios, again

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/ProductPage/styles.module.scss
> +
Guarda con los espacios innecesarios 3: Todopoderoso

2023-09-25 23:35 UTC, nathan-hyan commented on src/components/Slider/index.tsx
>  /* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
No dependas mucho de desactivar el eslint cuando llore, fíjate que esta pasando y lee la documentación que te ofrece así entendes el problema y lo solucionas

2023-09-25 23:35 UTC, nathan-hyan commented on src/scss/main.scss
> +
Guarda con los espacios 4: Resurrections

2023-09-25 23:35 UTC, nathan-hyan commented on src/scss/main.scss
> +    background-color: $gray !important;
Por que el `!important`? que esta jodiendo aca?

2023-09-25 23:49 UTC, JaqKent commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +                            onKeyDown={() => handleSearch(item.description)}
uso el onKeyDown porque me obliga no porque quiera usarlo

2023-09-25 23:51 UTC, JaqKent commented on src/components/ProductPage/components/ProductSearchScreen/index.tsx
> +                    discountPrice={product.discountPrice || undefined}
estas seguro que es innecesario? ya que eso puede no estar cuando se cargue un producto, puede venir como undefined, ademas si te fijas ya lo use de esa manera en un componente anterior para que renderice cuando un producto tenga delivery, descuenteo ,etc

2023-09-25 23:52 UTC, JaqKent commented on src/scss/main.scss
> +    background-color: $gray !important;
nada, estaba probando cosas y me olvide de sacarlo, ya lo corrijo

2023-09-26 00:01 UTC, nathan-hyan commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +                            onKeyDown={() => handleSearch(item.description)}
Cambiando el div a un button no te debería joder con eso

2023-09-26 00:03 UTC, nathan-hyan commented on src/components/ProductPage/components/ProductSearchScreen/index.tsx
> +                    discountPrice={product.discountPrice || undefined}
Es que si a estos params les pones el opcional (`discountPrice?: number`) en la interfaz, ya no es necesario que le pongas el undefined, porque el tipo seria: `number | undefined`

Por ende, el hecho de que pongas el `|| undefined` es redundante

2023-09-26 00:03 UTC, JaqKent commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +                    onClick={() => handleSearch(search)}
done

2023-09-26 00:04 UTC, JaqKent commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +        setSearch(searchItem);
done

2023-09-26 00:04 UTC, JaqKent commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +        navigate(`/productsearch/${searchItem}`);
done

2023-09-26 00:05 UTC, JaqKent commented on src/components/ProductPage/components/ProductSearchScreen/index.tsx
> +                    discountPrice={product.discountPrice || undefined}
ok, gracias por la explicacion, ya correji

2023-09-26 00:08 UTC, JaqKent commented on src/components/Slider/index.tsx
>  /* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
ok, done

2023-09-26 00:23 UTC, JaqKent commented on src/components/ProductPage/components/specifications/index.tsx
> +            </div>
done

2023-09-26 00:23 UTC, JaqKent commented on src/components/ProductPage/components/specifications/index.tsx
> +            </div>
done

2023-09-26 00:24 UTC, JaqKent commented on src/components/ProductPage/components/specifications/styles.module.scss
> +    @include flex (center, center, column);
done

2023-09-26 01:07 UTC, JaqKent commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +    }).slice(0, 10);
done

2023-09-26 01:07 UTC, JaqKent commented on src/components/NavigationBar/components/SearchBar/index.tsx
> +                            onKeyDown={() => handleSearch(item.description)}
corregido todo el div, cambiado por un button

2023-09-26 01:14 UTC, JaqKent commented on src/scss/main.scss
> +    background-color: $gray !important;
done

2023-09-26 01:14 UTC, JaqKent commented on src/scss/main.scss
> +
done

2023-09-26 01:14 UTC, JaqKent commented on src/components/ProductPage/styles.module.scss
> +
done

2023-09-26 01:14 UTC, JaqKent commented on src/components/ProductPage/styles.module.scss
> +
done

2023-09-26 01:14 UTC, JaqKent commented on src/components/ProductPage/styles.module.scss
> +
done

2023-09-26 01:14 UTC, JaqKent commented on src/components/ProductPage/styles.module.scss
> +
done

2023-09-26 01:14 UTC, JaqKent commented on src/components/ProductPage/components/specifications/styles.module.scss
>      @include flex (flex-start, flex-start, column);
done

2023-09-27 16:08 UTC, nathan-hyan approved these changes

2023-09-27 19:58 UTC, merged